# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 80, host: 81
  config.vm.network "forwarded_port", guest: 3000, host: 3001
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 16384
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"] # Speed up boot process
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL] # Speed up boot process
  end
end
